"use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./utils/providers/ReactQueryProvider";
import store, { persistor } from "./utils/reduxStore/store";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PersistGate persistor={persistor}>
          <Provider store={store}>
            <ReactQueryProvider>
              <main>{children}</main>
            </ReactQueryProvider>
          </Provider>
        </PersistGate>
      </body>
    </html>
  );
}
